CREATE DATABASE db;
USE db;

CREATE TABLE roles(
    id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE clients(
    id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE users(
    id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE products(
    id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE sells(
    id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE sold_products(
    id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE system_log(
    id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    user TEXT NOT NULL,
    registry TEXT NOT NULL,
    table_name TEXT NOT NULL,
    row_id INT NOT NULL,
    date_time DATETIME DEFAULT NOW()
);

ALTER TABLE roles
    ADD COLUMN name TEXT NOT NULL;

ALTER TABLE clients
    ADD COLUMN name TEXT NOT NULL,
    ADD COLUMN id_card TEXT NOT NULL;

ALTER TABLE users
    ADD COLUMN name TEXT NOT NULL,
    ADD COLUMN email TEXT NOT NULL,
    ADD COLUMN password TEXT NOT NULL,
    ADD COLUMN role_id INT(11) NOT NULL,
    ADD FOREIGN KEY (role_id) REFERENCES roles(id);

ALTER TABLE products
    ADD COLUMN name TEXT NOT NULL,
    ADD COLUMN description TEXT NOT NULL,
    ADD COLUMN cost INT(11) NOT NULL,
    ADD COLUMN sell_price INT(11) NOT NULL,
    ADD COLUMN quantiy INT(11) NOT NULL;

ALTER TABLE sold_products
    ADD COLUMN sell_id INT(11) NOT NULL,
    ADD COLUMN name TEXT NOT NULL,
    ADD COLUMN description TEXT NOT NULL,
    ADD COLUMN sell_price INT(11) NOT NULL,
    ADD COLUMN quantiy INT(11) NOT NULL,
    ADD FOREIGN KEY (sell_id) REFERENCES sells(id);

ALTER TABLE sells
    ADD COLUMN client_name TEXT NOT NULL,
    ADD COLUMN client_id_card TEXT NOT NULL,
    ADD COLUMN user_name TEXT NOT NULL,
    ADD COLUMN sell_datetime DATETIME DEFAULT NOW();