USE test;
CREATE TABLE IF NOT EXISTS users(
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user_insert TEXT NOT NULL,
	user_update TEXT NOT NULL,
	date_insert DATETIME NOT NULL DEFAULT NOW(),
	date_update DATETIME NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS clients(
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user_insert TEXT NOT NULL,
	user_update TEXT NOT NULL,
	date_insert DATETIME NOT NULL DEFAULT NOW(),
	date_update DATETIME NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS products(
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user_insert TEXT NOT NULL,
	user_update TEXT NOT NULL,
	date_insert DATETIME NOT NULL DEFAULT NOW(),
	date_update DATETIME NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS roles(
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user_insert TEXT NOT NULL,
	user_update TEXT NOT NULL,
	date_insert DATETIME NOT NULL DEFAULT NOW(),
	date_update DATETIME NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS sells(
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user_insert TEXT NOT NULL,
	user_update TEXT NOT NULL,
	date_insert DATETIME NOT NULL DEFAULT NOW(),
	date_update DATETIME NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS buys(
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user_insert TEXT NOT NULL,
	user_update TEXT NOT NULL,
	date_insert DATETIME NOT NULL DEFAULT NOW(),
	date_update DATETIME NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS providers(
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user_insert TEXT NOT NULL,
	user_update TEXT NOT NULL,
	date_insert DATETIME NOT NULL DEFAULT NOW(),
	date_update DATETIME NOT NULL DEFAULT NOW()
);

ALTER TABLE users
	ADD name TEXT NOT NULL,
	ADD email TEXT NOT NULL,
	ADD password TEXT NOT NULL,
	ADD age INT(8) NOT NULL,
	ADD ci TEXT NOT NULL,
	ADD role INT(11) NOT NULL;

ALTER TABLE products
	ADD name TEXT NOT NULL,
	ADD description TEXT NOT NULL,
	ADD cost DECIMAL(14,2) NOT NULL,
	ADD sell_price DECIMAL(14,2) NOT NULL,
	ADD quantity INT(11) NOT NULL;

ALTER TABLE roles
	ADD name TEXT NOT NULL,
	ADD description TEXT NOT NULL;

ALTER TABLE sells
	ADD product TEXT NOT NULL,
	ADD quantity INT(11) NOT NULL,
	ADD client INT(11) NOT NULL;

ALTER TABLE buys
	ADD product TEXT NOT NULL,
	ADD quantity INT(11) NOT NULL,
	ADD provider INT(11) NOT NULL;

ALTER TABLE clients 
	ADD name TEXT NOT NULL,
	ADD description TEXT NOT NULL,
	ADD email TEXT NOT NULL,
	ADD ruc TEXT NOT NULL;

ALTER TABLE providers 
	ADD name TEXT NOT NULL,
	ADD description TEXT NOT NULL,
	ADD email TEXT NOT NULL,
	ADD ruc TEXT NOT NULL;


