USE test;
CREATE TABLE IF NOT EXISTS users(
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user_insert INT(11) NOT NULL,
	user_update INT(11) NOT NULL,
	date_insert DATETIME NOT NULL DEFAULT NOW(),
	date_update DATETIME NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS clients(
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user_insert INT(11) NOT NULL,
	user_update INT(11) NOT NULL,
	date_insert DATETIME NOT NULL DEFAULT NOW(),
	date_update DATETIME NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS products(
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user_insert INT(11) NOT NULL,
	user_update INT(11) NOT NULL,
	date_insert DATETIME NOT NULL DEFAULT NOW(),
	date_update DATETIME NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS roles(
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user_insert INT(11) NOT NULL,
	user_update INT(11) NOT NULL,
	date_insert DATETIME NOT NULL DEFAULT NOW(),
	date_update DATETIME NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS sells(
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user_insert INT(11) NOT NULL,
	user_update INT(11) NOT NULL,
	date_insert DATETIME NOT NULL DEFAULT NOW(),
	date_update DATETIME NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS buys(
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user_insert INT(11) NOT NULL,
	user_update INT(11) NOT NULL,
	date_insert DATETIME NOT NULL DEFAULT NOW(),
	date_update DATETIME NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS providers(
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user_insert INT(11) NOT NULL,
	user_update INT(11) NOT NULL,
	date_insert DATETIME NOT NULL DEFAULT NOW(),
	date_update DATETIME NOT NULL DEFAULT NOW()
);


ALTER TABLE users
	ADD COLUMN name TEXT NOT NULL,
	ADD COLUMN email TEXT NOT NULL,
	ADD COLUMN password TEXT NOT NULL,
	ADD COLUMN age INT(8) NOT NULL,
	ADD COLUMN ci TEXT NOT NULL,
	ADD COLUMN role INT(11) NOT NULL;
ALTER TABLE products
	ADD COLUMN name TEXT NOT NULL,
	ADD COLUMN description TEXT NOT,
	ADD COLUMN cost FLOAT(11) NOT NULL,
	ADD COLUMN sell_price FLOAT(11) NOT NULL,
	ADD COLUMN quantity INT(11) NOT NULL;
ALTER TABLE roles
	ADD COLUMN name TEXT NOT NULL,
	ADD COLUMN description TEXT NOT;
ALTER TABLE sells
	ADD COLUMN product TEXT NOT NULL,
	ADD COLUMN quantity INT(11) NOT NULL,
	ADD COLUMN client INT(11) NOT NULL;
ALTER TABLE buys
	ADD COLUMN product TEXT NOT NULL,
	ADD COLUMN quantity INT(11) NOT NULL,
	ADD COLUMN provider INT(11) NOT NULL;
ALTER TABLE clients 
	ADD COLUMN name TEXT NOT NULL,
	ADD COLUMN description TEXT NOT NULL,
	ADD COLUMN email TEXT NOT NULL,
	ADD COLUMN ruc TEXT NOT NULL;
ALTER TABLE providers 
	ADD COLUMN name TEXT NOT NULL,
	ADD COLUMN description TEXT NOT NULL,
	ADD COLUMN email TEXT NOT NULL,
	ADD COLUMN ruc TEXT NOT NULL;
